FraudScanner.Web/Controllers/RuleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks; 
using FraudScanner.Web.Service;
using FraudScanner.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace FraudScanner.Web.Controllers
{
    public class RuleController : Controller
    {
        private readonly RuleMainService _ruleMainService;
        private readonly TransactionMainService _transactionMainService;

        public RuleController(RuleMainService ruleMainService,
            TransactionMainService transactionMainService)  
        {
            _ruleMainService = ruleMainService;
            _transactionMainService = transactionMainService;
        }

        public IActionResult Index()
        {
            //TempData["Message"] = "test";
            ViewBag.RuleTypes = _ruleMainService.GetRuleTypes();
            ViewBag.TransactionTypes = _transactionMainService.GetTransactionTypes();
            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            var newRule = new RuleViewModel();
            newRule.ActiveDate = new DateTime(2018, 1, 11);
            newRule.RuleTypes = new SelectList(
 
                _ruleMainService.GetRuleTypes(), "Id", "RuleTypeDesc");
            newRule.TransactionTypes = new SelectList(
                _transactionMainService.GetTransactionTypes(), "Id", "TransactionTypeDesc");

            return View("CreateEdit", newRule);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(RuleViewModel NewRule)
        {
            if (ModelState.IsValid)
            {
                _ruleMainService.AddRule(NewRule);

                TempData["Message"] = "Added New Rule";
                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.RuleTypes = new SelectList(

                    _ruleMainService.GetRuleTypes(), "Id", "RuleTypeDesc");
                ViewBag.TransactionTypes = new SelectList(
                    _transactionMainService.GetTransactionTypes(), "Id", "TransactionTypeDesc");

            }
            return View("CreateEdit", NewRule);
        }

        [HttpGet]
        public IActionResult Edit(long Id)
        {
            var editRule = _ruleMainService.GetRule(Id);
            editRule.RuleTypes = new SelectList( 
                _ruleMainService.GetRuleTypes(), "Id", "RuleTypeDesc");
            editRule.TransactionTypes = new SelectList(
                _transactionMainService.GetTransactionTypes(), "Id", "TransactionTypeDesc");

            return View("CreateEdit", editRule);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(long Id, RuleViewModel EditRule)
        {
            if (ModelState.IsValid)
            {
                _ruleMainService.UpdateRule(EditRule   );

                TempData["Message"] = "Added New Rule";
                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.RuleTypes = new SelectList(

                    _ruleMainService.GetRuleTypes(), "Id", "RuleTypeDesc");
                ViewBag.TransactionTypes = new SelectList(
                    _transactionMainService.GetTransactionTypes(), "Id", "TransactionTypeDesc");

            }
            return View("CreateEdit", EditRule);
        }

        public ActionResult GetRules(Nullable<int> RuleTypeId, Nullable<int> TransactionTypeId)
        {
            var ruleLst = _ruleMainService.GetRules(RuleTypeId, TransactionTypeId);
            var result = new
            {
                total = 1,
                page = 1,
                records = ruleLst.Count,
                rows = ruleLst
            };

            return Json(result);
        }
    }
}

FraudScanner.Web/Controllers/TransactionActivityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FraudScanner.Web.Service;
using Microsoft.AspNetCore.Mvc;

namespace FraudScanner.Web.Controllers
{
    public class TransactionActivityController : Controller
    {
        private readonly TransactionMainService _transactionMainService;

        public TransactionActivityController(TransactionMainService transactionMainService)
        { _transactionMainService = transactionMainService; }

        public IActionResult Index()
        {
            ViewBag.DefaultFromDateStr = DateTime.Now.AddMonths(-1).ToString("MM/dd/yyyy");
            ViewBag.DefaultToDateStr = DateTime.Now.ToString("MM/dd/yyyy");
            ViewBag.TransactionTypes = _transactionMainService.GetTransactionTypes();

            return View();
        }

        public ActionResult GetTransactions(Nullable<int> TransactionTypeId,
            Nullable<int> AccountId,
            DateTime FromDate,
            DateTime ToDate)
        {
            var transLst = _transactionMainService.GetTransactions(TransactionTypeId,
                AccountId, FromDate, ToDate);
            var result = new
            {
                total = 1,
                page = 1,
                records = transLst.Count,
                rows = transLst
            };
             
            return Json(result); 
        }

    }
}

FraudScanner.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    @{

//ViewData["DisplayMessage"] = (TempData.Peek("message") != null ? TempData("message") : "") ;
    }
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Fraud Scanner</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Fraud Scanner</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Rule" asp-action="Index">Rules</a></li>
                    <li><a asp-area="" asp-controller="TransactionActivity" asp-action="Index">Transactions</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content"> 
        @{ 
            if (@TempData.Peek("message") != null)
            {
        <span style="font-size: 18px;color:Green" id="MESSAGE_TOP">
            @TempData["message"]
        </span>
                } }
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Fraud Scanner</p>
        </footer>
    </div>

     
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>

        <script type="text/javascript">
            $(function () {
                $("#MESSAGE_TOP").delay(25000).slideUp(5000);
            });

        </script>
    </environment>
    <environment exclude="Development">
         
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
        <script type="text/javascript">
            $(function () {
                $("#MESSAGE_TOP").delay(25000).slideUp(5000);
            });

        </script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

FraudScanner.Web/Views/Shared/_ToFromDate.cshtml
@section scripts {
<script type="text/javascript">
    $(document).ready(function () {
        alert("test 12")
        set_dates();
    }
    );
    set_dates = function () {

         $("#FROM_DATE").datepicker({
            changeMonth: true,
            changeYear: true,
            dateFormat: 'mm/dd/yy',
            gotoCurrent: true
        });
        $("#FROM_DATE").attr('maxlength', '10');
        $("#FROM_DATE").val("@ViewData["fromdate"].ToString()");

        $("#TO_DATE").datepicker({
            changeMonth: true,
            changeYear: true,
            dateFormat: 'mm/dd/yy',
            gotoCurrent: true
        });
        $("#TO_DATE").attr('maxlength', '10');
        $("#TO_DATE").val("@ViewData["todate"].ToString()");
    });

    ToFromDate = {
        get_from_date_val : function()
        {
            return $("#FROM_DATE").val();
        },
        get_to_date_val : function()
        {
            return $("#TO_DATE").val();
        }
    }
</script> 
 }
@Html.TextBox("FROM_DATE", "", new { style = "width: 90px;" })
@Html.Label(" and ")
@Html.TextBox("TO_DATE", "", new { style = "width: 90px;" })
                    